# Changes here will be overwritten by Copier
_commit: 2.1.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: david.perl@diamond.ac.uk
author_name: David Perl
component_owner: group:default/sscc
description: A service to put and get your config values from
distribution_name: daq-config-server
docker: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: daq_config_server
pypi: true
repo_name: daq-config-server
type_checker: pyright
