# Changes here will be overwritten by Copier
_commit: 3.0.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: oliver.silvester@diamond.ac.uk
author_name: Oliver Silvester
component_lifecycle: experimental
component_owner: group:default/data-acquisition
component_type: service
description: A service to read files on dls_sw from a blueapi container
distribution_name: daq-config-server
docker: true
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: daq_config_server
pypi: true
repo_name: daq-config-server
strict_typing: true
type_checker: pyright
