apiVersion: v1
kind: Pod
metadata:
  name: container-service
spec:
  containers:
    - name: config-service
      image:
      command: ["container_service"]
      args: []
      resources:
        limits:
          cpu: "1"
          memory: 300M
    # - name: config-service-database
    #   image: valkey/valkey:7.2.5-alpine3.19
    #   command: ["container_service"]
    #   args: []
    #   resources:
    #     limits:
    #       cpu: "1"
    #       memory: 300M
