{{- if .Values.deployment.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daq-config-server
  namespace: {{ .Release.Namespace }}
  {{- with $.Values.deployment.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.deployment.podAnnotations }}
      annotations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels.matchLabels" $ | nindent 8 }}
    spec:
      containers:
        - name: daq-config-server
          image: {{ include "common.images.image" ( dict "imageRoot" $.Values.image "global" $.Values.global "chart" $.Chart ) }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- if .Values.deployment.commandOverride }}
          command:
            {{- .Values.deployment.commandOverride | toYaml | nindent 12 }}
          {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
          resources:
            {{- $.Values.deployment.resources | toYaml | nindent 12 }}
          {{- with $.Values.deployment.nodeSelector }}
          nodeSelector:
            {{- . | toYaml | nindent 8 }}
          {{- end }}
          {{- with $.Values.deployment.affinity }}
          affinity:
            {{- . | toYaml | nindent 8 }}
          {{- end }}
          {{- with $.Values.deployment.tolerations }}
          tolerations:
            {{- . | toYaml | nindent 8 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.deployment.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.deployment.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
{{- end}}
