apiVersion: v2
name: daq-config-server
description: A Helm chart for Kubernetes
type: application

# These are overridden for release builds by CI when the helm chart is published
version: 0.1.0
appVersion: "v0.2.0"
