# This whitelist defines the configuration files permitted for access by the site-wide
# config server at daq-config.diamond.ac.uk
# Beamlines with their own beamline-specific daq-config-server should define their own whitelists
# in the configmap for their own individual deployment.

#For long-term configuration files
whitelist_files:
- /tests/test_data/beamline_parameters.txt
# The following filepaths should be un-whitelisted once they've been moved to **/daq_configuration/
# See https://jira.diamond.ac.uk/browse/MXGDA-4204
- /dls_sw/i19-1/software/gda_versions/gda/config/xml/jCameraManZoomLevels.xml
- /dls_sw/i24/software/gda_versions/gda/config/xml/jCameraManZoomLevels.xml
- /dls_sw/i23/software/aithre/aithre_display.configuration
- /dls_sw/i23/software/aithre/aithre_oav.xml
- /dls_sw/i23/software/gda_versions/var/display.configuration
- /dls_sw/i24/software/gda_versions/var/display.configuration
- /dls_sw/i15-1/software/gda_var/xpdfLocalParameters.xml

#For long-term directories with frequently changing files
whitelist_dirs:
- /tests/test_data/
- /dls_sw/i02-1/software/daq_configuration/
- /dls_sw/i19-1/software/daq_configuration/
- /dls_sw/i19-2/software/daq_configuration/
- /dls_sw/i23/software/daq_configuration/
- /dls_sw/i24/software/daq_configuration/
- /dls_sw/i04-1/software/daq_configuration/
- /dls_sw/i10/software/gda/workspace_git/gda-diamond.git/configurations/i10-shared/
- /dls_sw/i09-1/software/gda/workspace_git/gda-diamond.git/configurations/i09-1-shared/lookupTables/
- /dls_sw/i09-2/software/gda/workspace_git/gda-diamond.git/configurations/i09-2-shared/lookupTables/
- /dls_sw/i21/software/gda/workspace_git/gda-diamond.git/configurations/i21-config/lookupTables/
- /dls_sw/i07/software/gda/config/lookupTables/
- /dls_sw/i07/software/gda/workspace_git/gda-diamond.git/configurations/i07-config/lookupTables/
- /dls_sw/i16/var/
- /dls_sw/i15-1/software/daq_configuration/
